// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1n3XveWj7Hvxiz4nT1Lfc9B6vKJ7pik',
    appId: '1:1014775181786:web:9f0c75d1cf9c8bd6bc90e3',
    messagingSenderId: '1014775181786',
    projectId: 'appborys',
    authDomain: 'appborys.firebaseapp.com',
    storageBucket: 'appborys.firebasestorage.app',
    measurementId: 'G-HNS8FT0YH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9QURLswr6SQN1Ph72TDXjrlisYZttnw',
    appId: '1:1014775181786:android:cea95a1afe6c5e14bc90e3',
    messagingSenderId: '1014775181786',
    projectId: 'appborys',
    storageBucket: 'appborys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDbRLkzUcFqiIBOVmtqo_ITreYiKFSlk',
    appId: '1:1014775181786:ios:97c4190336a07983bc90e3',
    messagingSenderId: '1014775181786',
    projectId: 'appborys',
    storageBucket: 'appborys.firebasestorage.app',
    iosBundleId: 'com.example.ultima2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDbRLkzUcFqiIBOVmtqo_ITreYiKFSlk',
    appId: '1:1014775181786:ios:97c4190336a07983bc90e3',
    messagingSenderId: '1014775181786',
    projectId: 'appborys',
    storageBucket: 'appborys.firebasestorage.app',
    iosBundleId: 'com.example.ultima2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC1n3XveWj7Hvxiz4nT1Lfc9B6vKJ7pik',
    appId: '1:1014775181786:web:903e66b8be1f9f54bc90e3',
    messagingSenderId: '1014775181786',
    projectId: 'appborys',
    authDomain: 'appborys.firebaseapp.com',
    storageBucket: 'appborys.firebasestorage.app',
    measurementId: 'G-LQ4LZ1TK5C',
  );
}
